version: "3"
services:
  "{{kebab name}}-ui":
    image: nginx
    container_name: "{{kebab name}}-ui"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    ports:
      - 80:80
    volumes:
      - "${{upper (snake name)}}_HOME/ui/apps:/srv/package"
      - "${{upper (snake name)}}_HOME/ui:/ui-config"
      - "${{upper (snake name)}}_HOME/ui/apps/ci-helpers:/setup"
      - "${{upper (snake name)}}_HOME/local-dev/nginx/certs:/srv/certs"
      - "${{upper (snake name)}}_HOME/local-dev/nginx/nginx.conf:/etc/nginx/nginx.conf"
