version: '3.3'
networks:
  aura-local-dev:
    external: true
services:
  {{kebab name}}-db:
    image: postgres
    restart: always
    container_name: {{kebab name}}-db
    environment:
      POSTGRES_USER: '{{kebab name}}'
      POSTGRES_PASSWORD: '{{kebab name}}'
    networks:
      - {{kebab name}}-local-dev
    ports:
      - '5432:5432'
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
